[package]
name = "pyothello"
version = "0.1.0"
edition = "2021"

[package.metadata.maturin]
python-source = "pyothello"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pyothello"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
