def _parse_kif(data: bytes) -> bytes: ...
def _parse_kif_with_check(data: bytes) -> bytes: ...
def _mk_kif(data: str) -> bytes: ...
def _read_kif(data: bytes) -> str: ...
def _rotate_kif(data: bytes) -> bytes: ...
def _miror_kif(data: bytes) -> bytes: ...
def _mk_data(data: list[int]) -> bytes: ...
def _put(data: bytes, pos: int) -> bytes: ...
def _put_opp(data: bytes, pos: int) -> bytes: ...
def _me_legal_moves(data: bytes) -> list[int]: ...
def _opp_legal_moves(data: bytes) -> list[int]: ...
def _legal_moves(data: bytes) -> list[list[int]]: ...
def _get(data: bytes, pos: int) -> int: ...
def _decode(data: bytes) -> list[int]: ...
def _make() -> bytes: ...
def _count(data: bytes) -> int: ...
def _counts(data: bytes) -> tuple[int, int]: ...
def _cns(data: bytes) -> tuple[int, int]: ...
def _edax(data: bytes) -> float: ...
def _pyindex(data: bytes, index: bytes) -> list[int]: ...
